# Generated by Django 5.1.7 on 2025-03-21 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('subscription_id', models.CharField(max_length=255)),
                ('paypal_subscription_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(max_length=50)),
                ('trial_end', models.DateTimeField(blank=True, null=True)),
                ('is_trial_active', models.BooleanField(default=True)),
            ],
        ),
    ]
