# Generated by Django 5.1.7 on 2025-03-27 18:34

import crawler.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0002_rename_is_trial_active_usersubscription_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubscription',
            name='paypal_subscription_id',
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='trial_end',
            field=models.DateTimeField(default=crawler.models.default_trial_end),
        ),
    ]
