# Generated by Django 5.1.7 on 2025-04-02 11:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0004_alter_usersubscription_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='status',
            field=models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('expired', 'Expired')], default='trial', max_length=20),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='trial_end',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 5, 11, 7, 20, 437807, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='user_id',
            field=models.IntegerField(unique=True),
        ),
    ]
