# Generated by Django 5.1.7 on 2025-04-02 17:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0005_alter_usersubscription_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='trial_end',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 5, 17, 32, 52, 736156, tzinfo=datetime.timezone.utc)),
        ),
    ]
